### ISSUE TITLE
Jinja wrong variable name in etc-ldap-libnss_conf.j2

### ISSUE THREAD

**Issue by aTanCS** [seb36273/openmediavault-ldap#5]
`etc-ldap-libnss_conf.j2` has a wrong variable name that breaks extraoptions setting.

```
{{ extraoptions }}
```
it should be
```
{{ config.extraoptions }}
```

**Comment by seb36273** [comment]
Was fixed with Commit 43864496bbb728016bcefb3622559ecce02528d1 from @ripkens. Many thanks!
